# #Promises
A promise will have an initial state of ‘pending’.
If promise is successful, it is said to be fulfilled and the function will be passed to `.then()`. Otherwise it is said to be rejected and will be passed to `.catch()`.

If you have an async function, it can be promisified using the new keyword with the Promise class. 

```js
const fetchMP3 = (track) => {
	return new Promise((resolve, reject) => {
		setTimeout(() => {
			if (err) reject('....')
			else resolve('....')
		}, Math.random()*2000);
}

fetchMP3(track)
	.then(MP3 => console.log(MP3)
// promises can be chained as long as the previous promise is returning a promise.
	.catch(err => console.log(err); 
```

The new promise needs to be returned so it can be passed to the next `.then()` or `.catch()` function.

```js
Promise.all([fetchMP3('Song1'), fetchMP3('Song2')]
	.then(outputArray => {
		// process outputArray
	}
	.catch(err => {
		// process error
	})
})
```

Promise.all takes an array of promisified functions and returns an array of results.
DON’T nest .then  within another .then block.


